config/routes.rb
Rails.application.routes.draw do
resources :labels, only: [:show]

 resources :topics do
    resources :posts, except: [:index]
  end
  
 # #4
   resources :posts, only: [] do
   resources :comments, only: [:create, :destroy]

     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   resources :favorites, only: [:create, :destroy]
   end
   
 resources :users, only: [:new, :create]

 resources :sessions, only: [:new, :create, :destroy]

 get 'about' => 'welcome#about'
 root to: 'welcome#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true
  after_create :send_favorite_emails
 
   private
 
   def send_favorite_emails
     post.favorites.each do |favorite|
       FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
     end
   end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/label.rb
 class Label < ActiveRecord::Base
   # #5
   has_many :labelings
 # #6
   belongs_to :labelable, polymorphic: true

  def self.update_labels(label_string)
     new_labels = []
 # #25
     unless label_string.nil? || label_string.empty?
 # #26
       label_string.split(",").each do |label|
       label_name = label.strip
       new_label = Label.find_or_create_by(name: label_name)
       new_labels << new_label
       end
     end
     new_labels
   end
 # #7
   has_many :topics, through: :labelings, source: :labelable, source_type: :Topic
 # #8
   has_many :posts, through: :labelings, source: :labelable, source_type: :Post
 end

app/models/labeling.rb
class Labeling < ActiveRecord::Base
  belongs_to :labelable, polymorphic: true
  belongs_to :label
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  after_create :create_favorite

  default_scope { order('rank DESC') }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true


   def up_votes
 # #9
     votes.where(value: 1).count
   end
 
   def down_votes
 # #10
     votes.where(value: -1).count
   end
 
   def points
 # #11
     votes.sum(:value)
   end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end

  def create_favorite
    Favorite.create(post: self, user: self.user)
    FavoriteMailer.new_post(self).deliver_now
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  enum severity: [ :PG, :PG13, :R ]

  belongs_to :rateable, polymorphic: true
  has_many :topics, source: :rateable, source_type: :Topic
  has_many :posts, source: :rateable, source_type: :Posts
  


  def self.update_rating(rating)
    Rating.find_or_create_by(severity: rating.to_i)
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  scope :publically_viewable, -> { where(public: true)}
  scope :privately_viewable, -> { where(public: false)}
  scope :visible_to, -> (user) { user ? all : publically_viewable }
end

app/models/user.rb
class User < ActiveRecord::Base
   has_many :posts, dependent: :destroy
   has_many :comments, dependent: :destroy
   has_many :votes, dependent: :destroy
   has_many :favorites, dependent: :destroy
   # #2
   before_save { self.email = email.downcase }
   before_save { self.role ||= :member }
 # #3
   EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

 # #4
  validates :name, length: { minimum: 1, maximum: 100 }, presence: true
 # #5
  validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true
 # #6
  validates :email,
             presence: true,
             uniqueness: { case_sensitive: true },
             length: { minimum: 3, maximum: 100 },
             format: { with: EMAIL_REGEX }

 # #7
   has_secure_password
   
   enum role: [:member, :admin]

   def favorite_for(post)
     favorites.where(post_id: post.id).first
   end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true
  
  private
 
  def update_post
    post.update_rank
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
 # #7
   before_action :require_sign_in, except: [:index, :show]
 # #8
   before_action :authorize_user, except: [:index, :show]

  def index
   @topics = Topic.visible_to(current_user)
  end


  def show
    @topic = Topic.find(params[:id])
     
     unless @topic.public || current_user
       flash[:error] = "You must be signed in to view private topics."
       redirect_to new_session_path
     end
  end

  def new
    @topic = Topic.new
  end 


   def create
     @topic = Topic.new(topic_params)
 
     if @topic.save
       @topic.labels = Label.update_labels(params[:topic][:labels])
       redirect_to @topic, notice: "Topic was saved successfully."
     else
       flash[:error] = "Error creating topic. Please try again."
       render :new
     end
   end


   def edit
     @topic = Topic.find(params[:id])
   end
  
   def update
     @topic = Topic.find(params[:id])
 
     @topic.assign_attributes(topic_params)
 
     if @topic.save
       @topic.labels = Label.update_labels(params[:topic][:labels])
       flash[:notice] = "Topic was updated."
       redirect_to @topic
     else
       flash[:error] = "Error saving topic. Please try again."
       render :edit
     end
   end
  def destroy
     @topic = Topic.find(params[:id])
 
     if @topic.destroy
       flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
       redirect_to action: :index
     else
       flash[:error] = "There was an error deleting the topic."
       render :show
     end
   end

   private
   def topic_params
     params.require(:topic).permit(:name, :description, :public)
   end
    
 # #9
   def authorize_user
     unless current_user.admin?
       flash[:error] = "You must be an admin to do that."
       redirect_to topics_path
     end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper

   def form_group_tag(errors, &block)
 # #5
     if errors.any?
       content_tag :div, capture(&block), class: 'form-group has-error'
     else
       content_tag :div, capture(&block), class: 'form-group'
     end
   end

   def avatar_url(user)
     gravatar_id = Digest::MD5::hexdigest(user.email).downcase
     "http://gravatar.com/avatar/#{gravatar_id}.png?s=48"
   end
end

app/helpers/comments_helper.rb
module CommentsHelper
   def user_is_authorized_for_comment?(comment)
      current_user && (current_user == comment.user || current_user.admin?)
   end
end

app/helpers/favorites_helper.rb
module FavoritesHelper

end

app/helpers/labels_helper.rb
module LabelsHelper
  def labels_to_buttons(labels)
      raw labels.map { |l| link_to l.name, label_path(id: l.id), class: 'btn-xs btn-primary' }.join(' ')
  end
end

app/helpers/posts_helper.rb
module PostsHelper
   def user_is_authorized_for_post?(post)
      current_user && (current_user == post.user || current_user.admin?)
   end
end

app/helpers/ratings_helper.rb
module RatingsHelper
  def rating_to_button(rating)
    link_to rating.severity, rating_path(id: rating.id), class: 'btn btn-rating'
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # #4
   def create_session(user)
     session[:user_id] = user.id
   end
 
 # #5
   def destroy_session(user)
     session[:user_id] = nil
   end
 
 # #6
   def current_user
     User.find_by(id: session[:user_id])
   end

end

app/helpers/topics_helper.rb
module TopicsHelper
   def user_is_authorized_for_topics?
        current_user && current_user.admin?
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/topics/_form.html.erb
 <%= form_for @topic do |f| %>
 <% if topic.errors.any? %>
     <div class="alert alert-danger">
       <h4><%= pluralize(topic.errors.count, "error") %>.</h4>
       <ul>
         <% topic.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
         </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>

app/views/topics/_topic.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to topic.name, topic %>
    </h4>
    <small>
      <%= topic.description %>
    </small>
    </div>
  </div>

app/views/topics/edit.html.erb
 <h1>Edit Topic</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @topic do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <div class="form-group">
         <%= render partial: 'labels/form', locals: { f: f, labels: @topic.labels } %>
       </div>
 
       <div class="form-group">
 
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/topics/index.html.erb
 <h1>Topics</h1>
 
 <div class="row">
   <div class="col-md-8">
 
     <% @topics.each do |topic| %>
       <%= render partial: 'topic', locals: { topic: topic} %>
     <% end %>
   </div>
  <% if user_is_authorized_for_topics? %>
   <div class="col-md-4">
     <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
   </div>
   <% end %>
 </div>

app/views/topics/new.html.erb
<h1>New Topic</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @topic do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <div class="form-group">
         <%= render partial: 'labels/form', locals: { f: f, labels: @topic.labels } %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/topics/show.html.erb
 <h1><%= @topic.name %></h1>

<% if user_is_authorized_for_topics? %>
 <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
 <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
<% end %>
 <div class="row">
   <div class="col-md-8">
     
     <p class="lead">
       <%= render partial: "labels/list", locals: { labels: @topic.labels } %>
       <br />
       <%= @topic.description %>
     </p>
     <% @topic.posts.each do |post| %>
       <div class="media">
         <%= render partial: 'votes/voter', locals: { post: post } %>
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to post.title, topic_post_path(@topic, post) %>
             <%= render partial: "labels/list", locals: { labels: post.labels } %>
           </h4>
          <small>
             submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
           </small>
             <%= post.comments.count %> Comments
         </div>
       </div>
     <% end %>
   </div>
  <% if current_user %>
   <div class="col-md-4">
    <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
     <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
   </div>
   <% end %>
 </div>